<a href="https://colab.research.google.com/github/carlosfmorenog/CMM560_Data_Loading_Tutorial/blob/main/CMM560_data_loading_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Remember to store the "data" folder in the same directory/path as this notebook

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Version 1: Converting your image repository into numpy arrays

In [ ]:
import os
import numpy as np
import cv2
resize_width = 100
resize_height = 100
path = 'data'
images = [] # List to append the images as 2D numpy arrays.
target = [] # List to append the target
originalrepo = [] # Create a repo for flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height)) 
                images.append(img)
                # Append the flattened image to the pixel repo
                originalrepo.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the repo list into numpy array
originalrepo = np.array(originalrepo) 
print(originalrepo)
print(target)

[[ 59  65  66 ... 127 132 111]
 [109 119 112 ...  12  14  34]
 [190 190 191 ...  38  37  38]
 [101 101 101 ... 178 176 182]
 [242 241 241 ...  38  41  43]
 [185 190 197 ... 146 146 146]]
['mask', 'mask', 'mask', 'mask', 'nomask', 'nomask']


# Version 2: Converting your image repository into Pandas data frames

In [ ]:
import os
import numpy as np
import cv2
from pandas import DataFrame

resize_width = 25
resize_height = 25
path = 'data'
images = [] # List to append the images as 2D numpy arrays
target =  []
originalrepo = [] # Create a repo for flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height)) 
                images.append(img)
                # Append the flattened image to the pixel repo
                originalrepo.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the repo list into pandas dataframe
originalrepowtarget = DataFrame(originalrepo) 
originalrepowtarget['class']=DataFrame(target)
originalrepowtarget

['mask', 'mask', 'mask', 'mask', 'nomask', 'nomask']


0    1    2    3    4    5    6    7    8    9  ...  616  617  618  619  \
0   63   83   49  108  188   11   28  109   49  126  ...  120  101  133  179   
1  137   40   80   92  161  123  135  128  194   72  ...   19   19  118   15   
2  190  192  190  192  192  190  193  192  198  146  ...   25   39   71   79   
3   97   95   92  160  153   78  165  198  118   96  ...  190  191  187  178   
4  243  240  240  239  238  236  236  237  237  235  ...  138  122   66   92   
5  206  155  149  153  153  153  151  153  152  153  ...  147  153  142  149   

   620  621  622  623  624   class  
0  178  136  127  117  128    mask  
1   18   15   30   24   12    mask  
2   67   52   45   44   41    mask  
3  176  181  185  181  182    mask  
4   50   18   41   42   42  nomask  
5  148  146  146  146  146  nomask  

[6 rows x 626 columns]

It is up to you to use the one you like the most!